config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks, except: [:index] do
    get 'delete'
  end

  root to: 'home#index'

  # Letter Opener Web UI
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  match '*path' => 'home#index', via: :all
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :title
  validate :future_completed_date
  validates_presence_of :user

  private

  def future_completed_date
    if !completed.blank? && completed > Date.today
      self.errors.add(:completed, "can't be in the future")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.accessible_by(current_ability).all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    render :show_task_modal
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    authorize! :create, @task
    save_task
  end

  def edit
    @task = Task.find(params[:id])
    authorize! :edit, @task
    render :show_task_modal
  end

  def update
    @task = Task.find(params[:id])
    @task.assign_attributes(task_params)
    authorize! :update, @task
    save_task
  end

  def delete
    @task = Task.find(params[:task_id])
    authorize! :edit, @task
    render :delete_task_modal
  end

  def destroy
    @task = Task.find(params[:id])
    authorize! :destroy, @task
    @task.destroy
    @tasks = Task.accessible_by(current_ability).all
    render :hide_task_delete
  end

  private

  def save_task
    if @task.save
      @tasks = Task.accessible_by(current_ability).all
      render :hide_task_modal
    else
      render :show_task_modal
    end
  end

  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.container.mt-5
  = link_to 'New task', new_task_path, class: 'btn btn-primary float-end mt-5 mb-3', remote: true

#task-list.container
  = render partial: "tasks/task_list", locals: { tasks: @tasks }

#showTaskModal.modal.fade aria-hidden="true" aria-labelledby="showTaskModal" tabindex="-1"
#deleteTaskModal.modal.fade aria-hidden="true" aria-labelledby="deleteTaskModal" tabindex="-1"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todo Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta content="maximum-scale=1.0, initial-scale=1.0, width=device-width" name="viewport" /
  body
    = render partial: "shared/navbar"
    = yield
    = render partial: "shared/footer"

app/views/shared/_footer.html.slim
footer.footer.mt-auto.py-3.bg-light.fixed-bottom
  .container.text-center
    a href="https://github.com/DonKennethVitug" class='text-decoration-none btn btn-link' target="_blank"
      i.fa.fa-github.me-1
      | DonKennethVitug

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    a.navbar-brand href="#" Todo Rails
    button.navbar-toggler aria-controls="navbarNav" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarNav" data-bs-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      ul.navbar-nav.ms-auto
        - if current_user
          li.nav-item
            = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item
            = link_to 'Login', new_session_path('user'), class: 'nav-link'
          li.nav-item
            = link_to 'Register', new_registration_path('user'), class: 'nav-link'

app/views/tasks/_task_delete.html.slim
.modal-dialog.modal-dialog-centered
  .modal-content
    .modal-header
      h5.modal-title
        | Delete Task
      button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
    .modal-body
      | Are you sure you want to delete "
      = @task.title
      | "?
    .modal-footer
      = link_to task_path(task), remote: true, method: 'DELETE', class: 'btn btn-danger'
        | Delete Task

app/views/tasks/_task_form.html.slim
= simple_form_for @task, class: 'clearfix', remote: true do |f|
  .modal-dialog.modal-dialog-centered
    .modal-content
      .modal-header
        h5.modal-title
          = @task.title ? 'Edit Task' : 'Create Task'
        button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
      .modal-body
        span.d-block
          = f.input :title, class: "form-control"
        span.d-block.mt-3
          = f.input :note, class: "form-control"
        span.d-block.mt-3
          = f.input :completed, as: :string, input_html: {class: 'datepicker'}, class: "form-control"
      .modal-footer
        = f.submit (@task.title ? 'Edit Task' : 'Create Task'), class: 'btn btn-primary'

app/views/tasks/_task_list.html.slim
- if tasks.empty?
  span
    | There are no tasks!
- else
  table.table.table-hover.table-bordered
    thead
      tr
        th
          | Title
        th
          | Created at
        th
          | Completed
        th
          | Actions
    tbody
      - tasks.each do |task|
        tr
          td
            strong
              = task.title
          td.text-info
            = task.created_at
          td.text-success
            = task.completed
          td.align-middle
            = link_to edit_task_path(task), remote: true do
              i.fa.fa-edit.me-2
            = link_to task_delete_path(task), remote: true
              i.fa.fa-trash

app/views/tasks/delete_task_modal.erb
m = $('#deleteTaskModal');
m.html('<%= j(render partial: 'task_delete', locals: {task: @task})%>');
m.modal('show');
$('#deleteTaskModal').integrateDatepicker();

app/views/tasks/hide_task_delete.js.erb
m = $('#deleteTaskModal');
m.modal('hide');
$('#deleteTaskModal').integrateDatepicker();
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');

app/views/tasks/hide_task_modal.js.erb
m = $('#showTaskModal');
m.modal('hide');
$('#showTaskModal').integrateDatepicker();
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');

app/views/tasks/show_task_modal.js.erb
m = $('#showTaskModal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task})%>');
m.modal('show');
$('#showTaskModal').integrateDatepicker();